# Generated by Django 5.2.5 on 2025-08-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='service_name',
            new_name='site_name',
        ),
    ]
